name = "GasModelsMultiPipeline"
uuid = "fe008eec-3dd3-44c3-8ca6-68c20413824e"
authors = ["Kaarthik Sundar <kaarthik@lanl.gov>", "David M Fobes <dfobes@lanl.gov"]
version = "0.1.1"

[deps]
GasModels = "5e113713-6c35-5477-b766-e1109486666f"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
GasModels = "~0.9"
InfrastructureModels = "~0.6"
Ipopt = "~0.6, ~0.7"
JuMP = "~0.21"
MathOptInterface = "~0.9"
julia = "^1.6"

[extras]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Ipopt", "Test", "MathOptInterface"]
